# -- DOCKER COMPOSE BUILD FOR REVERSE PROXY - ST -- #

services:

  #NGINX Reverse Proxy Service
  nginx-reverse-proxy:
    #Build from local Directory instead of Docker Hub Image
    build:
      context: ./nginx-image-config
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-image-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-image-config/ssl:/etc/nginx/ssl:ro
    networks:
      - monitor
    restart: unless-stopped

networks:
  monitor:
    driver: bridge
