global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['proxy-node-exporter:9100']

  - job_name: 'nginx-ingress'
    static_configs:
      - targets: ['proxy-nginx-exporter:9113']
